//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSiteWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_interest
    {
        public short int_id { get; set; }
        public string int_interest { get; set; }
    }
}
