//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSiteWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_experience
    {
        public short exp_id { get; set; }
        public string exp_title { get; set; }
        public string exp_subtitle { get; set; }
        public string exp_description { get; set; }
        public string exp_date { get; set; }
    }
}
