//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSiteWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_about
    {
        public short abt_id { get; set; }
        public string abt_name { get; set; }
        public string abt_surname { get; set; }
        public string abt_address { get; set; }
        public string abt_mail { get; set; }
        public string abt_tel { get; set; }
        public string abt_note { get; set; }
        public string abt_photo { get; set; }
        public string abt_linkedin { get; set; }
        public string abt_github { get; set; }
        public string abt_twitter { get; set; }
        public string abt_instagram { get; set; }
    }
}
