//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSiteWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_education
    {
        public short edc_id { get; set; }
        public string edc_title { get; set; }
        public string edc_subtitle { get; set; }
        public string edc_description { get; set; }
        public string edc_note { get; set; }
        public string edc_date { get; set; }
    }
}
