//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSiteWithMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_communication
    {
        public int cmt_id { get; set; }
        public string cmt_nameSurname { get; set; }
        public string cmt_email { get; set; }
        public string cmt_subject { get; set; }
        public string cmt_message { get; set; }
        public Nullable<System.DateTime> cmt_date { get; set; }
    }
}
